name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JSHint
      run: npm install jshint --global

    - name: Run Linter
      run: |
        find ./giftlink-backend -name "*.js" -exec jshint {} +
        echo "Linted all the js files successfully"

  client_build:
    name: Build client
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Create .env File
      run: |
        echo "REACT_APP_API_URL=https://your-api-url" > giftlink-frontend/.env

    - name: Install Dependencies
      run: |
        cd giftlink-frontend
        npm install

    - name: Run build
      run: |
        cd giftlink-frontend
        npm run build

    - name: Display Logs on Failure
      if: failure()
      run: cat /home/runner/.npm/_logs/*.log
